const productDetailsData = [
{
    "id": 1,
    "title": "HDPE PONTOON RECTANGLE CAGE",
    "slogan": "HDPE PONTOON RECTANGLE CAGE 6X4X4",
    "material": "HDPE",
    "brand":"Star Suppliers",
    "color": ["Blue", "Yellow", "Orange", "Gray"],
    "category": "Fish Farming Equipment",
    "size": "6X4X4",
    // "thickness": "-",
    "shape": "Rectangle",
    "stock": "In Stock",
    "countryOfOrigin": "India",
    "shortDescription1": "This compact and durable fish cage is designed for efficient aquaculture in lakes, reservoirs, or coastal waters. Made with high-quality HDPE pontoons, it offers strong buoyancy and long-lasting performance.",
    "shortDescription2":"HDPE floating fish cages designed for cage culture aquaculture with high durability and low maintenance.",
    "longDescription1": "Fish cage farming, also called cage culture, is a modern aquaculture method where fish are grown in floating cages placed in lakes, rivers, or reservoirs. These cages allow free water circulation while containing the fish, making feeding and harvesting efficient.",
    "longDescription2": "HDPE fish cages are widely used for cage fish farming due to their durability, corrosion resistance, and ability to withstand harsh weather conditions. Farmers can cultivate species like tilapia, carp, catfish, and sea bass efficiently in these cages. Cage culture fish farming reduces land use, lowers operational costs, and increases fish production, making it one of the most profitable aquaculture farming methods.",
    "longDescription3": "Fish cage farming (also called cage culture aquaculture) is transforming the way we produce fish worldwide. With the growing demand for protein-rich seafood, farmers are turning to floating fish cages as an efficient and sustainable method of aquaculture farming. By using HDPE fish cages, farmers can maximize production while minimizing operational costs.",
    "link": "https://www.indiamart.com/proddetail/6x4x4-meter-hdpe-aqucacultre-cage-2853147770333.html?sellerpreview=1",
    "image":  "/product/6X4/img01.webp"
    
  },
  {
    "id": 2,
    "title": "HDPE PONTOON RECTANGLE CAGE",
    "slogan": "HDPE PONTOON RECTANGLE CAGE 7.5X4X4",
    "material": "HDPE",
    "brand":"Star Suppliers",
    "color": ["Blue", "Yellow", "Orange", "Gray"],
    "category": "Fish Farming Equipment",
    "size": "7.5X4X4",
    // "thickness": "-",
    "shape": "Rectangle",
    "stock": "In Stock",
    "countryOfOrigin": "India",
    "shortDescription1": "Designed for medium to large-scale fish farming, this cage offers more space and reliable performance in all water conditions. Built with marine-grade HDPE, it ensures durability and fish safety.",
    "shortDescription2":"HDPE floating fish cage 7.5X4X4 for cage culture fish farming and aquaculture projects.",
    "longDescription1": "The Fish Cage 7.5X4X4 is designed for commercial aquaculture farming, providing a durable and cost-effective solution for cage culture fish farming. Made with high-strength HDPE pipes and anti-fouling nets, it ensures longer life and high yield in freshwater and brackish water environments.",
    "longDescription2": "Cage fish farming with HDPE floating fish cages like the 7.5X4X4 model allows farmers to optimize water resources and achieve higher fish stocking density. This model is widely used for tilapia, pangasius, seabass, and carps. It reduces land dependency and helps in sustainable aquaculture development. Farmers prefer HDPE cages due to their low maintenance, UV resistance, and cost-effectiveness compared to traditional ponds.",
    "longDescription3": "Aquaculture farming is rapidly growing across the globe, and fish cage 7.5X4X4 is one of the most popular choices among farmers. Designed with HDPE floating pipes and strong nylon nets, this cage provides a reliable solution for cage fish farming. It supports large-scale fish production while reducing land usage, making it ideal for modern aquaculture cage culture.",
    "link": "https://www.indiamart.com/proddetail/7-5x5x4-meter-hdpe-aqucacultre-cage-2853147770488.html?sellerpreview=1",
    "image": "/product/7.5X4/p2.png"
    ,
    "meta":{
      "title": "Aquaculture Fish Cage for Fish Farming | HDPE Cages",
      "description": "Buy HDPE floating fish cage 7.5X4X4 for cage culture aquaculture. Durable, cost-effective solution for fish farming. Ideal for freshwater and brackish water.",
    }
  },
  {
    "id": 3,
    "title": "HDPE PONTOON SQUARE  CAGE",
    "slogan": "HDPE PONTOON RECTANGLE CAGE 20X20X4.5",
    "material": "HDPE",
    "brand":"Star Suppliers",
    "color": ["Blue", "Yellow", "Orange", "Gray"],
    "category": "Fish Farming Equipment",
    "size": "20X20X4.5",
    // "thickness": "-",
    "shape": "Rectangle",
    "stock": "In Stock",
    "countryOfOrigin": "India",
    "shortDescription1": "Built for large-scale commercial fish farming, this spacious and sturdy cage offers excellent stability with durable HDPE pontoons.",
    "shortDescription2":"Premium HDPE fish cage 20X20X4.5 designed for aquaculture farming with durability, UV resistance, and low maintenance.",
   "longDescription1": "The fish cage 20X20X4.5 is one of the most popular models for commercial cage fish farming. Made from strong HDPE pipes, these floating fish cages are suitable for aquaculture farming in lakes, reservoirs, and coastal waters. The design ensures high fish stocking density, proper water circulation, and cost-effective fish production.",
   "longDescription2": "This 20X20X4.5 ft fish cage is widely used in cage culture fish farming due to its easy installation, durability, and long service life. HDPE cages resist corrosion, UV rays, and biofouling, making them ideal for both freshwater and marine aquaculture. Cage culture fish farming cost with this cage depends on stocking density, feed, and maintenance. Farmers can rear multiple species like tilapia, catla, rohu, seabass, and shrimp in these floating aquaculture fish cages.",
   "longDescription3": "The fish cage 20X20X4.5 is a highly durable solution for cage fish farming. Farmers who want to increase production through floating fish cages often choose this model for its stability, cost-effectiveness, and suitability for both freshwater and marine aquaculture. With the rise of aquaculture farming, HDPE fish cages like these are becoming essential for sustainable fish production.",
    "link": "https://www.indiamart.com/proddetail/20x20x4-5-meter-hdpe-aqucacultre-cage-2853149560412.html?sellerpreview=1",
    "image": "/product/20X20/p01.webp",
    "meta":{
      "title": "Fish Cage 20X20X4.5 for Aquaculture Farming | HDPE Floating Cages",
      "description": "Buy high-quality HDPE fish cage 20X20X4.5 for cage fish farming. Learn cost, benefits & setup of floating aquaculture fish cages.",
    }
  },


  
  {
    "id": 4,
    "title": "HDPE Floating Jetty",
    "slogan": "HDPE Floating Jetty",
    "material": "HDPE",
    "brand":"Star Suppliers",
    "color": ["Blue", "Yellow", "Orange", "Gray"],
    "category": "Floating Jetty/Floating Dock/Floating Platform",
    "size": "As per your requirement",
    // "thickness": "-",
    "shape": "As per your requiremen",
    "stock": "In Stock",
    "countryOfOrigin": "India",
    "shortDescription1": "The HDPE Floating Jetty is a versatile and robust floating structure that provides secure and steady access to bodies of water for multiple applications such as aquaculture, marinas, and leisure activities. Constructed from premium HDPE, it withstands corrosion and adjusts to diverse water environments.",
    "shortDescription2":"High-quality floating dock and pontoon jetty system suitable for marinas, fisheries, aquaculture, and water sports.",
    "longDescription1": "Our floating docks and pontoons are designed with advanced modular technology, ensuring strength, safety, and durability. Made from eco-friendly HDPE material, they are resistant to UV rays, saltwater corrosion, and heavy loads. Perfect for both commercial floating docks and recreational platforms.",
    "longDescription2": "These floating jetty systems can be customized for various applications, including aquaculture farms, yacht marinas, water sports, military bridges, and floating stages. The non-slip surface and interlocking modular design allow quick installation and easy maintenance. Whether you need a temporary or permanent water platform, our floating dock solutions provide the perfect balance of flexibility and reliability.",
    "longDescription3": "A floating dock is an innovative water platform designed for safe access, recreation, aquaculture, and commercial use. Whether it’s a floating pontoon, floating jetty, or commercial floating dock, these modular systems are becoming increasingly popular worldwide. Built with HDPE materials, they are lightweight, durable, and resistant to environmental damage, making them the go-to solution for marinas, fisheries, and water sports facilities.",
    "link": "https://www.indiamart.com/proddetail/hdpe-floating-jetty-walkway-2853147771873.html?sellerpreview=1",
    "image": "/product/jetty/Floating Jetty.webp",
    "meta":{
      "title": "Floating Dock & Pontoon Jetty | Durable Water Platforms",
      "description": "Discover durable floating docks, pontoons, and jetties for commercial and recreational use. Explore water platforms built with HDPE and modular designs.",
    }
  },
  {
    "id": 5,
    "title": "Floating Restaurant",
    "slogan": "Floating Restaurant",
    "material": "HDPE",
    "brand":"Star Suppliers",
    "color": ["Blue", "Yellow", "Orange", "Gray"],
    "category": "Floating Restaurant",
    "size": "As per your requirement",
    // "thickness": "-",
    "shape": "As per your requirement",
    "stock": "In Stock",
    "countryOfOrigin": "India",
    "shortDescription1": "The Floating Restaurant presents a creative approach to providing a lavish dining experience on water. Built on high-buoyancy pontoons, it merges stability with visual charm, making it ideal for lakes, rivers, and coastal regions.",
    "shortDescription2":"Perfect for upscale dining, relaxed cafés, or hosting events, this floating eatery elevates any eco-tourism or waterfront establishment. With adjustable size choices, it serves as a unique draw for resorts, aquaculture restaurants, and picturesque locations.",
    "longDescription1": "Floating restaurants are an innovative hospitality concept where dining spaces are built on floating pontoons. They offer a unique blend of luxury, tourism, and sustainability, attracting both locals and international tourists. With eco-friendly materials like HDPE floats, marine-grade Aluminum, and wooden finishes, these restaurants ensure durability and style.",
    "longDescription2": "Business owners are investing in floating restaurants to boost tourism and create new dining experiences. They can be designed in different sizes and shapes, accommodating 50 to 500 guests. Floating restaurants are suitable for lakes, rivers, marinas, and coastal areas. They provide not just dining but also entertainment, live music, and event hosting opportunities.",
    "longDescription3": "A floating restaurant is more than just a dining place—it is an experience on water. Built on floating pontoons or docks, these restaurants provide a luxury atmosphere while being eco-friendly and sustainable. From romantic dinners on lakes to family-friendly floating cafes, this innovative concept is reshaping the hospitality and aqua tourism industry.",
    "link": "https://www.indiamart.com/star-suppliers-bilaspur/products.html",
    "image": "/product/restaurant/rest1.webp",
    "meta":{
      "title": "Floating Restaurant| Experience Dining on Water",
      "description": "Discover floating restaurants, their benefits, design, and business opportunities. Learn why floating dining is the future of luxury and eco-friendly hospitality.",
    }
  },
  { 
    "id": 6,
    "title": "Dewatering System",
    "slogan": "Dewatering System",
    "material": "HDPE",
    "brand":"Star Suppliers",
    "color": ["Blue", "Yellow", "Orange", "Gray"],
    "category": "Dewatering System",
    "size": "As per your requirement",
    // "thickness": "-",
    "shape": "As per your requirement",
    "stock": "In Stock",
    "countryOfOrigin": "India",
    "shortDescription1": "Our Active Dewatering Platforms over a floating, modular solution for water removal from mining pits, or reservoirs.",
    "shortDescription2":"Mounted with submersible or centrifugal pumps, these floating units ensure uninterrupted pumping as water levels rise or fall.",
    "longDescription1": "Dewatering systems in mines help remove groundwater and surface water to ensure operational efficiency, safety, and sustainability.",
    "longDescription2": "Different types of systems include pump-based, gravity drainage, vacuum-assisted, and wellpoint dewatering. Each system ensures continuous productivity in open-pit and underground mining.",
    "longDescription3": "A dewatering system in mine is an essential part of modern mining operations. It is used to remove groundwater or surface water from mine shafts, tunnels, and open pits to ensure safe and efficient excavation. Without proper mine dewatering, excess water can lead to unstable slopes, equipment damage, reduced productivity, and even safety hazards. Modern mining industries adopt advanced dewatering pumps, slurry pumps, submersible pumps, and drainage systems to manage water effectively.",
    "link": "https://www.indiamart.com/star-suppliers-bilaspur/products.html",
    "image": "/product/dewatering-system/dewatering-system.webp",
    "meta":{
      "title": "Dewatering System in Mine – Process, Types & Benefits",
      "description": "Learn about dewatering systems in mining, their types, benefits, and efficiency in groundwater control for safe and sustainable mining operations.",
    }
  },
  {
    "id": 7,
    "title": "HDPE Double Floating Pontoon",
    "slogan": "HDPE Double Floating Pontoon",
    "material": "HDPE",
    "brand":"Star Suppliers",
    "color": ["Blue", "Yellow", "Orange", "Gray"],
    "category": "HDPE Pontoon",
    "size": "1000x500x400 MM",
    "thickness": "Wall Thickness- 5 mm, Lugs Thickness- 20-25 mm, Weight-15.5Kg(±5%),Weight Bearing Capacity- 350Kg(±5% /per sq.mtr)",
    "shape": "",
    "stock": "In Stock",
    "countryOfOrigin": "India",
    "shortDescription1": "High-quality HDPE Square Pontoon designed for efficient fish farming with durable construction and long-lasting usability.",
    "shortDescription2":"Durable HDPE double pontoon floats for floating docks and pontoon bridges.",
    "longDescription1": "Our floating pontoon range includes heavy-duty double pontoon floats, modular floating docks, and double pontoon bridges built with HDPE for maximum strength and stability.", 
    "longDescription2": "These floating dock and pontoon bridge systems are resistant to UV rays, corrosion, and impact, making them ideal for commercial marinas, aquaculture, resorts, and private watercraft docking.", 
    "longDescription3": "Applications of Floating Pontoon Systems, Floating Double Docks – Provide strong platforms for boats, yachts, and water sports equipment.,Double Pontoon Bridges – Ideal for connecting shores, industrial sites, or temporary event setups.,Aquaculture Platforms – Widely used in fish farms and water-based agriculture.,Resort & Leisure Projects – Floating walkways, sunbathing platforms, and recreational water spaces.",
    "link": "https://www.indiamart.com/proddetail/hdpe-double-floating-pontoon-2853149559548.html",
    "image": "/product/Accessories/double pontoon.webp",
    "meta":{
      "title": "Floating Double Pontoon Dock & Bridge Solutions",
      "description": "Explore HDPE floating pontoon systems: double pontoon floats, floating docks, and pontoon bridges. Durable, modular, and built for water access.",}
  },
  {
    "id": 7,
    "title": "Hexagonal Single Pontoon",
    "slogan": "Hexagonal Single Pontoon",
    "material": "HDPE",
    "brand":"Star Suppliers",
    "color": ["Blue", "Yellow", "Orange", "Gray"],
    "category": "HDPE Pontoon",
    "size": "600x600x500 MM",
    "thickness": "Wall Thickness- 5 mm, Lugs Thickness- 20-25 mm, Weight-7.5Kg(±5%),Weight Bearing Capacity- 350Kg(±5% /per sq.mtr)",
    "shape": "Hexagonal",
    "stock": "In Stock",
    "countryOfOrigin": "India",
    "shortDescription1": "A strong and versatile floating block with a unique hexagonal design for flexible layouts and better load distribution. Made from high-quality HDPE, it resists UV, corrosion, and tough marine conditions.",
    "shortDescription2":"High-buoyancy floating pontoon modules for docks, bridges and walkways.",
    "longDescription1": "Our floating pontoon systems include single pontoon floats designed for compact water access, modular floating docks built with pontoon floats offering easy assembly, and floating single dock units ideal for small boats or kayaks.", 
    "longDescription2": "Ideal for private and commercial use, our pontoon bridge and floating dock systems feature UV-stable HDPE construction, corrosion-resistant fittings, and optional aluminum sub-framing. The floating single pontoon units can handle pedestrian or light vehicle load, and expand into longer walkways with additional modules.",
    "longDescription3": "Single pontoon bridge segments may be 600 mm wide and 600 mm long, 500 mm Deep. Floating single dock units can hold light loads like kayaks or paddleboards stackable to form longer walkways. The modular design means you tailor length and width.",
    "image": "/product/Accessories/hexagonal.webp",
    "meta":{
      "title": "HDPE Hexagonal Single Pontoon for Modular Floating Docks",
      "description": "Discover durable HDPE hexagonal pontoons for docks, bridges, and walkways. UV-resistant, easy to install, and perfect for modular floating systems.",
    }
  },
  {
    "id": 8,
    "title": "HDPE Anti-Skid Single Pontoon",
    "slogan": "HDPE Anti-Skid Single Pontoon",
    "material": "HDPE",
    "brand":"Star Suppliers",
    "color": ["Blue", "Yellow", "Orange", "Gray"],
    "category": "HDPE Pontoon",
    "size": "500x500x400 MM",
    "thickness": "Wall Thickness- 5 mm, Lugs Thickness- 20-25 mm, Weight-7.5Kg(±5%), Weight Bearing Capacity- 350Kg(±5% /per sq.mtr)",
    "shape": "",
    "stock": "In Stock",
    "countryOfOrigin": "India",
    "shortDescription1": "A sturdy HDPE floating block with a textured, slip resistant top for maximum safety—even when wet. It&apos;s one piece design makes it light, easy to handle, and quick to install, yet strong enough to support heavy loads.",
    "shortDescription2":"HDPE Anti-Skid pontoons and floating docks designed for safe and stable marine use.",
    "longDescription1": "Our HDPE Anti-Skid floating pontoon range includes non-slip pontoon floats, floating docks, single pontoons, and pontoon bridges. These are built for marine projects, aquaculture, resorts, and leisure platforms.", 
    "longDescription2": "Made with UV-resistant HDPE, our pontoons are slip-proof, corrosion-free, and modular. The Anti-Skid design ensures safety for pedestrians, while strong buoyancy makes them ideal for floating single docks, aquaculture cages, and single pontoon bridges.", 
    "longDescription3": "Slip-Free Surface: Anti-skid design prevents accidents, ensuring safety for children, adults, and workers.Durability: HDPE resists UV rays, saltwater, and impact.Eco-Friendly: 100% recyclable and safe for marine life.Modular & Customizable: Build docks, bridges, or platforms in any shape or size.",
    "image": "/product/Accessories/Single-pontoon.webp",
    "meta":{
      "title": "HDPE Anti-Skid Floating Pontoon & Dock Systems",
      "description": "Discover durable HDPE Anti-Skid pontoons, floats, docks, and bridges. Non-slip, modular, and safe for marine, aquaculture, and leisure use.",
    }
  },
  {
    "id": 9,
    "title": "HDPE Top Cover Single Pontoon",
    "slogan": "HDPE Top Cover Single Pontoon",
    "material": "HDPE",
    "brand":"Star Suppliers",
    "color": ["Blue", "Yellow", "Orange", "Gray"],
    "category": "HDPE Pontoon",
    "size": "500x500x400 MM",
    "thickness": "Wall Thickness- 5 mm, Lugs Thickness- 20-25 mm,Top-Cover Thickness - 5mm Weight-7.5Kg(±5%), Weight Bearing Capacity- 350Kg(±5% /per sq.mtr)",
    "shape": "",
    "stock": "In Stock",
    "countryOfOrigin": "India",
    "shortDescription1": "A strong HDPE floating block with a reinforced top cover for added durability, load distribution, and a smooth, stable surface. Built to resist UV, corrosion, and harsh weather, it’s ideal for docks, floating stages, and industrial or leisure water setups.",
    "shortDescription2":"Premium HDPE Top Cover floating pontoons designed for docks, marinas, aquaculture & floating bridges.",
    "longDescription1": "HDPE Top Cover floating pontoons are durable, UV-resistant and environmentally friendly solutions for building floating docks, bridges and aquaculture platforms. These pontoons provide exceptional buoyancy, modular flexibility and safety for long-term use in fresh and saltwater environments.",
    "longDescription2": "Our single pontoon floats and HDPE Top Cover docks are easy to assemble, lightweight, and corrosion-resistant. Ideal for fish farming, floating restaurants, tourism, and water sports platforms. Designed with high load capacity, non-slip surface, and customizable color options.",
    "longDescription3": "Durability & Longevity – HDPE pontoons are corrosion-resistant, UV-stabilized, and built for long-term performance in both fresh and saltwater.Eco-Friendly & Safe – Non-toxic, recyclable material that is safe for aquatic life.Easy Installation – Modular design allows quick assembly for floating docks, bridges, and single pontoons.Versatility – Suitable for aquaculture cages, marina docks, floating restaurants, and tourism projects.Cost-Effective – Long service life with minimal maintenance compared to traditional wooden or steel pontoons.",
    "image": "/product/Accessories/single-pontoon-top-cover.webp",
    "meta":{
      "title": "HDPE Top Cover Floating Pontoon & Single Pontoon Solutions",
      "description": "Explore HDPE Top Cover floating pontoon, pontoon floats, docks & bridges. Durable, modular & eco-friendly solutions for aquaculture, marinas & tourism.",
    }
  },
  {
    "id": 10,
    "title": "HDPE Nursery Net 6X4X4",
    "slogan": "Nursery Net 6X4X4",
    "material": "HDPE Net",
    "brand":"Star Suppliers",
    "color": ["Blue", "Yellow", "Orange", "Gray"],
    "category": "HDPE Net",
    "size": "48 Ply| Mesh Size: 10 MM | Feed Screen 1M",
    "specification": "-",
    "shape": "",
    "stock": "In Stock",
    "countryOfOrigin": "India",
    "shortDescription1": "A strong, UV-stabilised net designed for fish and shrimp nurseries. It offers a safe, well-ventilated space for young stock, protecting them from predators and supporting healthy growth.",
    "shortDescription2":"Premium HDPE Nursery Net 6X4X4 for aquaculture and net cage fish farming.",
    "longDescription1": "The Aquaculture HDPE Nursery Net 6X4X4 is designed for professional fish farmers who need durable, UV-stabilized, and eco-friendly nets. With high tensile strength and water-resistant properties, this fish cage net provides optimal protection and growth environment for fish breeding and nursery farming.",
    "longDescription2": "This fish farming net is suitable for freshwater and marine aquaculture. It helps reduce fish mortality, prevents predator attacks, and ensures better yield. The HDPE nursery net is lightweight yet strong, easy to install, and cost-effective. Farmers looking for long-lasting aquaculture cage nets prefer this product for sustainable fish farming.",
    "longDescription3": "Key benefits include: UV-stabilized and eco-friendly design, Long-lasting and resistant to wear and tear, Protects fish from predators, Easy installation and maintenance, Cost-effective solution for fish farming nets.",
    "link": "https://www.indiamart.com/proddetail/aquaculture-cages-nursery-nets-6x4x4-2856619774148.html?sellerpreview=1",
    "image": "/product/Accessories/nur.webp",
    "meta":{
      "title": "HDPE Nursery Net 6X4X4 for Fish Farming | Best Price",
      "description": "Buy durable Aquaculture HDPE Nursery Net 6X4X4 fish cage nets for fish farming. Affordable prices, strong netting, and long-lasting performance.",
    }
  },
  {
    "id": 11,
    "title": "HDPE Nursery Net 7.5X4X4",
    "slogan": "Nursery Net 7.5X4X4",
    "material": "HDPE Net",
    "brand":"Star Suppliers",
    "color": ["Blue", "Yellow", "Orange", "Gray"],
    "category": "HDPE Net",
    "size": "48 Ply, Mesh Size: 10 mm, Feed Screen: 1 Meter",
    "specification": "-",
    "shape": "",
    "stock": "In Stock",
    "countryOfOrigin": "India",
    "shortDescription1": "Built for efficient nursery management, this durable 12-ply net provides a safe, well-ventilated space for juvenile fish. The 10 mm mesh allows good water flow while securely containing fingerlings.",
    "shortDescription2":"Premium HDPE nursery net for aquaculture cage farming.",
    "longDescription1": "The HDPE Nursery Net 7.5X4X4 is designed for fish cage farming, fish breeding, and aquaculture applications. It offers high durability, UV resistance, and long life in freshwater and marine environments.",
    "longDescription2": "This fish cage net is ideal for small and large-scale fish farmers. It ensures secure fish culture, prevents escape, and minimizes predator attacks. The affordable fish farming net price makes it suitable for both beginners and commercial aquaculture businesses.",
    "longDescription3": "Benefits of Using HDPE Fish Cage Nets Durability & Strength – HDPE nets are stronger than traditional nylon nets. UV & Weather Resistant – Designed to withstand direct sunlight and harsh aquatic environments. Cost-Effective – Affordable fish farming net prices make them suitable for both small and large farms. Easy Maintenance – The smooth surface prevents algae growth and biofouling. Safe for Fish Breeding – The fish breeding net design ensures secure breeding and minimizes losses.",
    "link": "https://www.indiamart.com/proddetail/aquaculture-cages-nursery-nets-7-5x4x4-2856619774391.html?sellerpreview=1",
    "image": "/product/Accessories/nur.webp",
    "meta":{
      "title": "HDPE Nursery Net 7.5X4X4 for Aquaculture | Fish Cage Nets",
      "description":"Buy high-quality HDPE Nursery Net 7.5X4X4 for fish farming. Durable aquaculture cage nets at affordable prices. Ideal for net cage fish farming & breeding."
    }
  },
  {
    "id": 12,
    "title": "HDPE Grow Out Net 6X4X4",
    "slogan": "HDPE Grow Out Net 6X4X4",
    "material": "HDPE Net",
    "brand":"Star Suppliers",
    "color": ["Blue", "Yellow", "Orange", "Gray"],
    "category": "HDPE Net",
    "size": "48 Ply | Mesh Size: 30 MM | Feed Screen 1M",
    "specification": "-",
    "shape": "",
    "stock": "In Stock",
    "countryOfOrigin": "India",
    "shortDescription1": "Designed for the grow-out phase, this heavy-duty 48-ply net is ideal for larger fingerlings and adult fish. The 30 mm mesh ensures strong water flow, while the 1-meter feed screen makes feeding easy and low-stress.",
    "shortDescription2":"Premium HDPE Grow Out Net designed for aquaculture and fish cage farming.",
    "longDescription1": "The Aquaculture HDPE Grow Out Net 6X4X4 is built from high-density polyethylene, providing superior strength, UV resistance, and long-lasting performance. It is designed for sustainable net cage fish farming and ensures optimal water flow, reducing fish stress and improving health.",
    "longDescription2": "Ideal for freshwater and marine aquaculture, this HDPE fish cage net is widely used in commercial fish farming, breeding, and research facilities. With affordable fish farming net price and customizable options, it is a perfect solution for professional aquaculture projects.",
    "longDescription3": "Aquaculture is growing rapidly as a sustainable solution for global fish demand. Among the essential tools for modern fish farmers is the HDPE Grow Out Net 6X4X4, a specially designed fish cage net that ensures durability, flexibility, and cost-effectiveness. Whether you are setting up net cage fish farming, planning a fish breeding net, or exploring the best fish farming net price, choosing the right aquaculture cage nets is critical for productivity and long-term success.",
    "link": "https://www.indiamart.com/proddetail/aquaculture-cages-growout-nets-6x4x4-2856619739033.html?sellerpreview=1",
    "image": "/product/Accessories/growout-net.webp",
    "meta":{
      "title": "Aquaculture HDPE Grow Out Net 6X4X4 for Fish Cage Farming ",
      "description": "Buy Aquaculture HDPE Grow Out Net 6X4X4 at best price. Strong, durable fish cage nets for fish farming, aquaculture & breeding. Check fish farming net price today.",
    }
  },
  {
    "id": 13,
    "title": "HDPE Grow Out Net 7.5X4X4",
    "slogan": "HDPE Grow Out Net 7.5X4X4",
    "material": "HDPE Net",
    "brand":"Star Suppliers",
    "color": ["Blue", "Yellow", "Orange", "Gray"],
    "category": "HDPE Net",
    "size": "48 Ply | 30 MM | Feed Screen 1M",
    "specification": "-",
    "shape": "",
    "stock": "In Stock",
    "countryOfOrigin": "India",
    "shortDescription1": "Ideal for the grow-out stage, this net provides ample space and excellent water flow for healthy fish development. The 30 mm mesh supports maturing fish, while the 1-meter feed screen ensures easy, low-stress feeding.",
    "shortDescription2":"Durable HDPE grow-out net designed for aquaculture cage farming.",
    "longDescription1": "The HDPE Grow Out Net 7.5X4X4 is designed for sustainable fish farming. It ensures fish safety, reduces escapes, and supports large-scale aquaculture operations.",
    "longDescription2": "This aquaculture cage net is UV-resistant, anti-predatory, and suitable for both freshwater and seawater farming. Farmers rely on its strength, flexibility, and affordability.",
    "longDescription3": "Aquaculture HDPE Grow Out Net 7.5X4X4 netting is one of the most trusted solutions for modern fish farmers. Designed specifically for net cage fish farming, this HDPE (High-Density Polyethylene) net is durable, UV-stabilized, and resistant to harsh water conditions. Whether you are looking for an affordable fish cage net price or a long-lasting fish breeding net, the 7.5X4X4 HDPE net is a perfect choice for aquaculture entrepreneurs.",
    "link": "https://www.indiamart.com/proddetail/aquaculture-cages-growout-nets-7-5x4x4-2856619739191.html?sellerpreview=1",
    "image": "/product/Accessories/growout-net.webp",
    "meta":{  
      "title": "Aquaculture HDPE Grow Out Net 7.5X4X4 for Fish Farming",
      "description": "Buy HDPE Grow Out Net 7.5X4X4 for fish farming. Durable, UV-stabilized netting for aquaculture cage farming. Affordable fish cage net price.",
    }
  },
  {
    "id": 13,
    "title": "HDPE Grow Out Net 20X20X4.5",
    "slogan": "HDPE Grow Out Net 20X20X4.5",
    "material": "HDPE Net",
    "brand":"Star Suppliers",
    "color": ["Black" ,  "Orange", "Green"],
    "category": "HDPE Net",
    "size": "132 Ply | 264 Ply | Mesh Size: 40 MM | Feed Screen 1M",
    "specification": "-",
    "shape": "",
    "stock": "In Stock",
    "countryOfOrigin": "India",
    "shortDescription1": "Built for large-scale aquaculture, this heavy-duty 132-ply net offers strength, space, and durability for raising mature fish. The 45 mm mesh ensures excellent water flow, while the 1-meter feed screen allows easy, low-stress feeding.",
    "shortDescription2":"Premium HDPE Grow Out Net 20X20X4.5 for fish cage farming and aquaculture.",
    "longDescription1": "The Aquaculture HDPE Grow Out Net 20X20X4.5 is designed for durability, strength, and long-term use in fish farming. Made from UV-stabilized high-density polyethylene, this net ensures maximum protection for fish stock while withstanding harsh marine environments.",
    "longDescription2": "Whether you are into commercial fish cage farming, aquaculture, or fish breeding projects, this net provides the perfect solution. Its anti-fouling, anti-corrosive, and knotless design reduces fish injury while improving water circulation. The affordable fish cage net price makes it an ideal choice for small-scale and large-scale aquaculture businesses.",
    "longDescription3": "Durability – Manufactured with high-density polyethylene (HDPE) for long-lasting performance. UV Protection – Resistant to sun damage and seawater corrosion. Safe for Fish – Knotless design prevents injuries to fish. Optimal Size – Standard size of 20X20X4.5 ensures easy setup in aquaculture cages. Cost-Effective – Competitive fish farming net price for commercial and small-scale farmers.",
    "link": "https://www.indiamart.com/proddetail/aquaculture-cages-growout-nets-20x20x4-5-2856619739309.html?sellerpreview=1",
    "image": "/product/Accessories/growout-net.webp",
    "meta":{
      "title": "Aquaculture HDPE Grow Out Net 20X20X4.5 | Fish Cage Nets",
      "description": "Buy durable Aquaculture HDPE Grow Out Net 20X20X4.5 for fish farming. Affordable fish cage net price with UV-stabilized HDPE material for aquaculture.",
    }
  },
  {
    "id": 14,
    "title": "HDPE Bird Net 6X4X4",
    "slogan": "HDPE Bird Net 6X4X4",
    "material": "HDPE Net",
    "brand":"Star Suppliers",
    "color": ["Blue", "Yellow", "Orange", "Black"],
    "category": "HDPE Net",
    "size": "18 Ply Mesh | Size: 50 MM",
    "specification": "-",
    "shape": "",
    "stock": "In Stock",
    "countryOfOrigin": "India",
    "shortDescription1": "Keep birds away from your fish stock with this lightweight yet durable 18-ply net. The 50 mm mesh offers effective protection while allowing air and light through.",
    "shortDescription2":"Premium HDPE Bird Net 6X4X4 designed for aquaculture cage farming.",
    "longDescription1": "Aquaculture HDPE Bird Net 6X4X4 is widely used in fish cage farming to protect fish from predators and birds. Made of UV-stabilized high-density polyethylene, this net ensures long durability, resistance to sunlight, and high tensile strength. It is suitable for freshwater and marine aquaculture projects.",
    "longDescription2": "These fish farming nets are lightweight, easy to install, and cost-effective. Farmers prefer HDPE nets due to their long lifespan, resistance to abrasion, and reduced maintenance cost. The 6X4X4 net is ideal for small and medium-scale aquaculture cage systems, ensuring maximum fish growth and reduced fish mortality.",
    "longDescription3": "The HDPE Bird Net 6X4X4 is a square-shaped fish farming net made of high-density polyethylene (HDPE). It is designed for net cage fish farming, where fish are raised in controlled environments. The netting is UV stabilized, corrosion-resistant, and highly durable, making it suitable for both freshwater and marine aquaculture systems.",
    "link": "https://www.indiamart.com/proddetail/aquaculture-cages-bird-protection-nets-6x4x4-2856619773655.html?sellerpreview=1",
    "image": "/product/Accessories/Bird-protection-net01.webp",
    "meta":{
      "title": "Aquaculture Cage Bird Nets 6X4X4 for Fish Farming",
      "description": "Buy high-quality aquaculture HDPE Bird Net 6X4X4 for fish farming cages. Learn price, benefits & uses of durable netting for aquaculture.",
    }
  },
  {
    "id": 14,
    "title": "HDPE Bird Net 7.5X4X4",
    "slogan": "HDPE Bird Net 7.5X4X4",
    "material": "HDPE Net",
    "brand":"Star Suppliers",
    "color": ["Blue", "Yellow", "Orange", "Black"],
    "category": "HDPE Net",
    "size": "18 Ply | Mesh: 50 mm",
    "specification": "-",
    "shape": "",
    "stock": "In Stock",
    "countryOfOrigin": "India",
    "shortDescription1": "This sturdy 18-ply bird net offers reliable protection for aquaculture setups by keeping birds away from your stock. The 50 mm mesh ensures safety without blocking airflow or sunlight.",
    "shortDescription2":"Premium HDPE fish cage net designed for aquaculture and breeding.",
    "longDescription1": "The Aquaculture HDPE Bird Net 7.5X4X4 is a high-quality netting solution for fish farming, cage culture, and aquaculture ponds. Made with UV-stabilized HDPE material, it ensures long-lasting durability and protection against predators.",
    "longDescription2": "This fish farming net provides strong resistance to water pressure, reduces fish escape, and promotes healthy breeding. Its lightweight yet strong structure makes it easy to install and maintain, making it a preferred choice among fish farmers across India and overseas.",
    "longDescription3": "Aquaculture is one of the fastest-growing sectors in food production, and reliable netting solutions are essential for successful fish farming. The Aquaculture HDPE Bird Net 7.5X4X4 is a widely used option for cage culture, providing strength, durability, and affordability. Farmers searching for fish cage nets, aquaculture nets, or fish farming nets often prefer HDPE nets because they are UV-resistant, lightweight, and long-lasting. In this article, we will discuss the benefits, applications, and fish cage net price of HDPE netting for aquaculture.",
    "link": "https://www.indiamart.com/proddetail/aquaculture-cages-bird-protection-nets-7-5x4x4-2856619773733.html?sellerpreview=1",
    "image": "/product/Accessories/Bird-protection-net01.webp",
    "meta":{
      "title": "Aquaculture HDPE Bird Net 7.5X4X4 for Fish Farming",
      "description": "Buy Aquaculture HDPE Bird Net 7.5X4X4 for fish farming. Durable fish cage nets, affordable price, and long-lasting netting for aquaculture & breeding.",
    }
  },
  {
    "id": 15,
    "title": "HDPE Bird Net 20X20X5",
    "slogan": "HDPE Bird Net 20X20X5",
    "material": "HDPE Net",
    "brand":"Star Suppliers",
    "color": ["Blue", "Yellow", "Orange", "Gray"],
    "category": "HDPE Net",
    "size": "Mesh Size 150 mm | 18-ply ",
    "specification": "-",
    "shape": "",
    "stock": "In Stock",
    "countryOfOrigin": "India",
    "shortDescription1": "Premium HDPE bird net designed for aquaculture cage fish farming.",
    "shortDescription2":"Easy to install and low-maintenance, it’s a reliable choice for safeguarding your fish stock across large areas.",
    "longDescription1": "The Aquaculture HDPE Bird Net 20X20X5 is specially designed for fish cage farming and aquaculture projects. Made with UV-stabilized high-density polyethylene, it ensures durability, strength, and long life in water environments.",
    "longDescription2": "This fish cage net is widely used for net cage fish farming, fish breeding, and aquaculture cages. It prevents bird attacks, reduces fish loss, and provides excellent water flow. The HDPE net is lightweight, easy to install, and resistant to seawater corrosion, making it the ideal choice for sustainable aquaculture.",
    "longDescription3": "Aquaculture is growing rapidly, and one of the most important tools for modern fish farming is the Aquaculture HDPE Bird Net 20X20X5. Farmers use these strong fish farming nets to protect their stock from predators and ensure safe breeding conditions. Choosing the right fish cage net not only prevents bird attacks but also enhances water flow and fish health. This article explains the benefits, features, and prices of HDPE fish cage nets for aquaculture projects.",
    "link": "https://www.indiamart.com/proddetail/aquaculture-cage-bird-protection-net-20x20x4-5-2856814726633.html?sellerpreview=1",
    "image": "/product/Accessories/Bird-protection-net01.webp",
    "meta":{
      "title": "HDPE Bird Net 20X20X5 for Fish Farming Cages",
      "description": "Buy durable Aquaculture HDPE Bird Net 20X20X5 for fish cage farming. Strong, UV-stabilized fish farming nets at the best price.",
    }
  },
  {
    "id": 15,
    "title": "HDPE Nut and Bolt",
    "slogan": "HDPE Nut and Bolt",
    "material": "HDPE Nut and Bolt",
    "brand":"Star Suppliers",
    "color": ["Blue", "Yellow", "Orange", "Gray"],
    "category": "HDPE Nut and Bolt",
    "size": "As per standard ",
    // "specification": "-",
    "shape": "",
    "stock": "In Stock",
    "countryOfOrigin": "India",
    "shortDescription1": "Made from durable, corrosion-resistant HDPE, these lightweight fasteners are perfect for securing pontoons, cages, nets, and other aquaculture setups.",
    "shortDescription2":"Versatile nut bolt and plastic fastener range including HDPE plastic nut bolt options.",
    "longDescription1": "Our nut bolt range includes HDPE High Definition Polyethylene nut and bolt fasteners, as well as plastic bolt, plastic nut and bolt, and specialized HDPE plastic nut bolt variants. Ideal for industrial, electrical, and corrosive environments.",
    "longDescription2": "These fasteners offer lightweight, corrosion-resistant, and non-conductive advantages. Manufacturers produce in nylon, HDPE, ABS, polypropylene, and other engineering plastics, tailored for specific load-bearing and environment-resistant applications.",
    "longDescription3": "The term nut bolt refers to one of the most common mechanical fasteners used across industries. From nut and bolt sets in heavy construction to plastic bolt and plastic nut and bolt fasteners used in electronics and corrosive environments, the right fastener matters. HDPE plastic nut bolt options offer lightweight, chemical-resistant solutions where metallic corrodes. This guide delves into types, benefits, and manufacturer insights while optimizing for search terms related to nut bolt, plastic fasteners, and HDPE bolt solutions.",
    "link": "https://www.indiamart.com/star-suppliers-bilaspur/products.html",
    "image": "/product/Accessories/nut-bolt.webp",
    "meta":{
      "title": "Nut Bolt & HDPE Plastic Nut | HDPE Fasteners",
      "description": "Discover types of nut bolt, HDPE nut and bolt, and HDPE HDPE fasteners. Explore benefits, manufacturers, and buying guide here.",
    }
  },
  {
    "id": 16,
    "title": "HDPE Center Pin",
    "slogan": "HDPE Center Pin",
    "material": "HDPE Center Pin",
    "brand":"Star Suppliers",
    "color": ["Blue", "Yellow", "Orange", "Gray"],
    "category": "HDPE Center Pin",
    "size": " As per standard",
    // "thickness": "-",
    "shape": "",
    "stock": "In Stock",
    "countryOfOrigin": "India",
    "shortDescription1": "Made from tough, UV- and corrosion-resistant HDPE, this center pin is built to securely connect modular pontoons and floating structures.",
    "shortDescription2": "Lightweight, weatherproof, and easy to install, it’s ideal for long-term use in aquaculture, docks, and water platforms—reliable and maintenance-free.",
    "longDescription1": "Our Center Pin range includes traditional HDPE Center Pin fasteners, as well as plastic bolt, plastic nut and bolt, and specialized HDPE plastic nut bolt variants. Ideal for industrial, electrical, and corrosive environments.",
    "longDescription2": "These fasteners offer lightweight, corrosion-resistant, and non-conductive advantages. Manufacturers produce in nylon, HDPE, ABS, polypropylene, and other engineering plastics, tailored for specific load-bearing and environment-resistant applications.",
    "longDescription3": "The term nut bolt refers to one of the most common mechanical fasteners used across industries. From nut and bolt sets in heavy construction to plastic bolt and plastic nut and bolt fasteners used in electronics and corrosive environments, the right fastener matters. HDPE plastic nut bolt options offer lightweight, chemical-resistant solutions where metallic corrodes. This guide delves into types, benefits, and manufacturer insights while optimizing for search terms related to nut bolt, plastic fasteners, and HDPE bolt solutions.",
    "link": "https://www.indiamart.com/star-suppliers-bilaspur/products.html",
    "image": "/product/Accessories/center-pin.webp",
    "meta":{
      "title": "Nut Bolt & HDPE  Nut | HDPE Fasteners",
      "description": "Discover types of nut bolt, HDPE nut and bolt, and HDPE HDPE fasteners. Explore benefits, manufacturers, and buying guide here.",
    }
  },
  {
    "id": 17,
    "title": "HDPE Railings",
    "slogan": "HDPE Railings",
    "material": "HDPE Railings",
    "brand":"Star Suppliers",
    "color": ["Blue", "Yellow", "Orange", "Gray"],
    "category": "HDPE Railings",
    "size": " As per standard",
    // "thickness": "-",
    "shape": "",
    "stock": "In Stock",
    "countryOfOrigin": "India",
    "shortDescription1": "Durable, UV- and corrosion-resistant, these HDPE railings are built for safety and stability on floating docks, aquaculture platforms, and walkways.",
    "shortDescription2":"HDPE railing for cage culture and jetty applications, ensuring safety and durability in marine conditions.",
    "longDescription1": "HDPE Railing is specially designed for aquaculture cages and floating jetties. Made from high-density polyethylene, it offers excellent resistance to corrosion, UV rays, and harsh marine environments. Lightweight yet strong, these railings are easy to install and require minimal maintenance.",
    "longDescription2": "Whether for fish cage farming, floating docks, or marine tourism infrastructure, HDPE railings provide reliable safety barriers. Unlike steel or wooden alternatives, HDPE does not rust, rot, or require frequent painting. Its long lifespan makes it a cost-effective solution for aquaculture and waterfront projects.",
    "longDescription3": "When it comes to safe and long-lasting marine infrastructure, HDPE Railing is one of the most reliable solutions. Whether it’s for cage railing in aquaculture farms or jetty railing in waterfront projects, HDPE (High-Density Polyethylene) has become the preferred choice. Its durability, UV resistance, and low maintenance make it an excellent alternative to traditional steel or wooden railings.",
    "link": "https://www.indiamart.com/proddetail",
    "image": "/product/Accessories/hdpe-railing.webp",
    "meta":{
      "title": "HDPE Railing for Cages & Jetties | Durable HDPE Railing",
      "description": "Discover durable HDPE railing for cage farming and jetties. Safe, lightweight, and long-lasting HDPE railing for aquaculture and waterfront projects.",
    }
  },
  {
    "id": 18,
    "title": "Stainless Steel Railings",
    "slogan": "Stainless Steel Railings",
    "material": "Stainless Steel Railings",
    "brand":"Star Suppliers",
    // "color": ["Blue", "Yellow", "Orange", "Gray"],
    "category": "Stainless Steel Railings",
    "size": " As per standard",
    // "thickness": "-",
    "shape": "",
    "stock": "In Stock",
    "countryOfOrigin": "India",
    "shortDescription1": "Crafted from high-grade stainless steel, these railings offer strong, rust-resistant support for floating docks, pontoons, and aquaculture walkways.",
    "shortDescription2":"High-quality stainless steel railings designed for aquaculture cages and floating jetties. Rust-proof, durable, and safe for marine conditions.",
    "longDescription1": "Stainless steel railings for aquaculture cages and jetties provide maximum durability and safety in harsh marine conditions. Made from SS 304 or SS 316 grade, these railings are resistant to corrosion, ensuring long life and minimum maintenance. Whether you are setting up a fish cage, floating dock, or jetty, stainless steel railings add stability and protection for workers and visitors.",
    "longDescription2": "These railings are custom-designed to fit aquaculture projects of all sizes. With polished finishing and anti-slip fittings, they enhance safety and aesthetics. Stainless steel railings are widely preferred in aquaculture and mariculture projects because they withstand constant exposure to seawater and humidity. They are easy to install, maintain, and integrate with floating pontoons, cages, and walkways.",
    "longDescription3": "Aquaculture and mariculture projects require strong, safe, and long-lasting infrastructure. Stainless steel railings for aquaculture cages and floating jetties are the preferred choice for ensuring safety and durability in harsh marine environments. Unlike mild steel or wooden structures, stainless steel (SS 304/316 grade) railings resist rust, corrosion, and saltwater damage, making them an essential component for fish farmers and marine tourism operators.",
    "link": "https://www.indiamart.com/proddetail/stainless-steel-railings-for-aquaculture-cages-jetties-2856619774083.html?sellerpreview=1",
    "image":"/product/Accessories/ss.webp",
    "meta":{
      "title": "Stainless Steel Railings for Aquaculture Cages & Jetties",
      "description": "Durable stainless steel railings for aquaculture cages & floating jetties. Corrosion-resistant, safe, and ideal for Aquaculture environments.",
    }
  },
]
export default productDetailsData;